// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4mtU9EGhT33SaGgwB2XSp12dcDzDdyU',
    appId: '1:603397324730:web:16f248a38bd53655732783',
    messagingSenderId: '603397324730',
    projectId: 'closet-851a3',
    authDomain: 'closet-851a3.firebaseapp.com',
    storageBucket: 'closet-851a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYboppQWRnx_kICUoiKLFzqa5SLfA9Euk',
    appId: '1:603397324730:android:35518db1a4c938c2732783',
    messagingSenderId: '603397324730',
    projectId: 'closet-851a3',
    storageBucket: 'closet-851a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyGPUTr6N8GxToM4Mv7RNX664OgfnVdA',
    appId: '1:603397324730:ios:02f74cffb126004a732783',
    messagingSenderId: '603397324730',
    projectId: 'closet-851a3',
    storageBucket: 'closet-851a3.appspot.com',
    iosClientId:
        '603397324730-jk2kis13fcjs8hatunot7g1299i92u5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalcloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyGPUTr6N8GxToM4Mv7RNX664OgfnVdA',
    appId: '1:603397324730:ios:fd9d7a67000b3249732783',
    messagingSenderId: '603397324730',
    projectId: 'closet-851a3',
    storageBucket: 'closet-851a3.appspot.com',
    iosClientId:
        '603397324730-70lsqa1a6g5cblc2vliggibsug46rf6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalcloset.RunnerTests',
  );
}
